var exports = module.exports = {};

exports.isarray = require('isarray');
exports['is-extendable'] = require('is-extendable');
exports['arr-diff'] = require('arr-diff');
exports['array-unique'] = require('array-unique');
exports['concat-map'] = require('concat-map');
exports['arr-flatten'] = require('arr-flatten');
exports['repeat-element'] = require('repeat-element');
exports['arrify'] = require('arrify');
exports['array-union'] = require('array-union');
exports['longest'] = require('longest');
exports['foreach'] = require('foreach');
exports['array-find-index'] = require('array-find-index');
exports['indexof'] = require('indexof');
exports['arr-union'] = require('arr-union');
exports['flatten'] = require('flatten');
exports['indexes-of'] = require('indexes-of');
exports['uniqs'] = require('uniqs');
exports['array-differ'] = require('array-differ');
exports['arraybuffer.slice'] = require('arraybuffer.slice');
exports['array-equal'] = require('array-equal');
exports['to-array'] = require('to-array');
exports['array-filter'] = require('array-filter');
exports['cyclist'] = require('cyclist');
exports['array-map'] = require('array-map');
exports['array-reduce'] = require('array-reduce');
exports['array-each'] = require('array-each');
exports['expand-braces'] = require('expand-braces');
exports['multimatch'] = require('multimatcharray-find');
exports['array-find'] = require('array-find');
exports['os-filter-obj'] = require('os-filter-obj');

